---
title: "GEQ Analysis"
author: "Monika Lind"
date: "2/26/2019"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(tidyverse)
library(rio)
library(here)
library(colorspace)
library(lubridate)
library(colorblindr)
library(gt)
library(ggforce)
```

```{r import}
d <- rio::import(here::here("Lind_GS_F18.csv"), setclass = "tbl_df") %>% 
  characterize()

names(d) <- str_replace_all(names(d), c("[.]" = "_", "Q" = "q"))
```

```{r tidy}
geq_raw <- d %>%
  mutate(pid = row_number()) %>% 
  select(119, everything())  %>% 
  rename(date = RecordedDate,
         duration = Duration__in_seconds_,
         race_ethn = q6,
         gender = q62,
         gender_text = q62_4_TEXT,
         age = q63) %>% 
  select(1:3, 6:7, 9:37)

geq_m <- geq_raw %>% 
  filter(gender == 2) %>% 
  select(1:22, 27:30) %>% 
  rename(gp_1 = q70_1,
         gp_2 = q70_2,
         gp_3 = q70_3,
         gp_4 = q70_4)

geq_f <- geq_raw %>% 
  filter(gender == 1) %>% 
  select(1:26) %>% 
  rename(gp_1 = q69_1,
         gp_2 = q69_2,
         gp_3 = q69_3,
         gp_4 = q69_4)

geq_nb <- geq_raw %>% 
  filter(gender == 3 | gender == 4 | gender == 5) %>% 
  select(1:22, 31:34) %>% 
  rename(gp_1 = q71_1,
         gp_2 = q71_2,
         gp_3 = q71_3,
         gp_4 = q71_4)

geq_wide <- bind_rows(geq_m, geq_f, geq_nb)

geq_tidy <- geq_wide %>% 
  rename(sr_1 = q65_1,
         sr_2 = q65_2,
         sr_3 = q65_3,
         sr_4 = q65_4,
         scob_1 = q66_1,
         scob_2 = q66_2,
         scob_3 = q66_3,
         scob_4 = q66_4,
         scob_5 = q66_5,
         inf_1 = q67_1,
         inf_2 = q67_2,
         inf_3 = q67_3,
         wfp_1 = q68_1,
         wfp_2 = q68_2,
         wfp_3 = q68_3,
         wfp_4 = q68_4) %>% 
  gather(item, response, -1:-6) %>% 
  separate(item, c("subscale", "item"), sep = "_") %>% 
  mutate(gender = as.factor(gender),
         subscale = as.factor(subscale),
         age = age + 15)
```

```{r sum_score}
geq_tidy %>%
  group_by(pid) %>% 
  summarize(sum_score = sum(response, na.rm = TRUE)) %>% 
  ggplot() +
  geom_histogram(aes(sum_score), binwidth = 10, alpha = .7, fill = "purple")
```

```{r sum_score_by_gender}
geq_tidy %>%
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid, gender) %>% 
  summarize(sum_score = sum(response, na.rm = TRUE)) %>% 
  ggplot() +
  geom_histogram(aes(sum_score, fill = gender), binwidth = 10, alpha = .7) +
  facet_wrap(~gender) +
  scale_fill_OkabeIto()

geq_tidy %>%
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid, gender) %>% 
  summarize(sum_score = sum(response, na.rm = TRUE)) %>% 
  ggplot(aes(sum_score, fill = gender)) +
  geom_histogram(alpha = .7, binwidth = 10, position = "identity") +
  scale_fill_OkabeIto()

geq_tidy %>%
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid, gender) %>% 
  summarize(sum_score = sum(response, na.rm = TRUE)) %>% 
  ggplot(aes(sum_score, fill = gender)) +
  geom_density(alpha = .7) +
  scale_fill_OkabeIto()
```

```{r subscale_score_by_gender}
geq_tidy %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid, subscale) %>% 
  mutate(sub_score = sum(response)) %>% 
  group_by(subscale, gender) %>% 
  summarize(n = n(), 
            mean = sum(sub_score, na.rm = TRUE)/n) %>% 
  ggplot(aes(subscale, mean, fill = gender)) + 
  geom_col(position = "dodge", color = "white", alpha = .7) +
  scale_fill_OkabeIto()

geq_tidy %>% 
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid, subscale) %>% 
  mutate(sub_score = sum(response, na.rm = TRUE)) %>% 
  ggplot(aes(subscale, sub_score, color = gender)) +
  geom_jitter(alpha = .5) +
  scale_color_OkabeIto()
```

```{r total_score_by_age}
geq_tidy %>%
  filter(gender == 1 | gender == 2) %>% 
  group_by(pid) %>% 
  mutate(sum_score = sum(response, na.rm = TRUE)) %>% 
  group_by(age) %>% 
  mutate(mean_by_age = mean(sum_score)) %>% 
  ggplot(aes(age, sum_score, group = age)) +
  geom_boxplot(alpha = .3) +
  geom_point(aes(color = gender), alpha = .5) +
  scale_color_OkabeIto()

geq_tidy %>%
  filter(gender == 1) %>% 
  group_by(pid) %>% 
  mutate(sum_score = sum(response, na.rm = TRUE)) %>% 
  group_by(age) %>% 
  mutate(mean_by_age = mean(sum_score)) %>% 
  ggplot(aes(age, sum_score, group = age)) +
  geom_boxplot() +
  geom_point() +
  scale_y_continuous(limits = c(0, 100))
```
